services:
  - type: web
    name: streamlit-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: startCommand: "streamlit run app.py --server.port $PORT"
